name: Build the image and scan the image
on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

    workflow_dispatch: 

jobs:
  docker-image-build-scan-push:

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker Login
        uses: docker/login-action@v3.2.0 #(MonishaNelson/Devsecops-Angular/actions/docker-scan@master)
        with:
          username: monishanelson
          password: Moni1305!
      -
        name: Docker Build
        run: | 
          docker build -t my-express-app1:express-app1 .
          docker tag my-express-app1:express-app1 monishanelson/devsecops_accelerator:express-app1
          docker push monishanelson/devsecops_accelerator:express-app1
      -
        name: Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: monishanelson/devsecops_accelerator:express-app1
          #security-checks: 'vuln,secrets,config'
          vuln-type: 'os,library'
          format: 'sarif'
          #exit-code: '1'
          output: 'trivy-image-results.sarif'
          severity: HIGH,CRITICAL
      
      #- name: Upload Trivy scan results to GitHub Security tab
        #uses: github/codeql-action/upload-sarif@v3.25.6
        #with:
          #sarif_file: 'trivy-results.sarif'
          #category: 'image'
      - name: Save SARIF file
        run: |
            mkdir -p /tmp/artifacts
            cp trivy-image-results.sarif /tmp/artifacts/
            ls /tmp/artifacts/
            cat /tmp/artifacts/trivy-image-results.sarif


            
          


     
      
         
          




    
